# Generated by Django 5.2.3 on 2025-06-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField()),
                ('mood', models.CharField(max_length=50)),
                ('view_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
